insert into sampledata.months ( id, name,temp,humi )
VALUES( 1, 'Canada',10,60 );
insert into sampledata.months ( id, name,temp,humi )
VALUES( 2, 'Mexico',12,50 );
insert into sampledata.months ( id, name,temp,humi )
VALUES( 3, 'Germany',15,80 );
insert into sampledata.months ( id, name,temp,humi )
VALUES( 4, 'France',30,55 );
insert into sampledata.months ( id, name,temp,humi )
VALUES( 5, 'Italy',20,67 );